package Modelos;
// Generated 12/11/2015 08:24:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seguridades generated by hbm2java
 */
public class Seguridades  implements java.io.Serializable {


     private Integer idSeguridad;
     private String nombre;
     private Set madreses = new HashSet(0);

    public Seguridades() {
    }

	
    public Seguridades(String nombre) {
        this.nombre = nombre;
    }
    public Seguridades(String nombre, Set madreses) {
       this.nombre = nombre;
       this.madreses = madreses;
    }
   
    public Integer getIdSeguridad() {
        return this.idSeguridad;
    }
    
    public void setIdSeguridad(Integer idSeguridad) {
        this.idSeguridad = idSeguridad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMadreses() {
        return this.madreses;
    }
    
    public void setMadreses(Set madreses) {
        this.madreses = madreses;
    }


 @Override
    public String toString() {
        return nombre; //To change body of generated methods, choose Tools | Templates.
    }

}


